from typing import TypedDict, List

class GraphState(TypedDict):
    """
    This is the 'shared notepad' that travels through our graph.
    Every node can read from it and write new information to it.
    """
    user_query: str
    context: List[str]  # A list of text chunks retrieved from ChromaDB
    final_answer: str   # The Marathi response generated by Sarvam AI